### ISSUE TITLE
Document hostDisks

### ISSUE THREAD

**Issue by rmohr** [kubevirt/user-guide#123]
`hostDisk` is not yet documented at https://kubevirt.io/user-guide/#/workloads/virtual-machines/disks-and-volumes?id=volumes

**Comment by rmohr** [comment]
@mfranczy could you have a look?

**Comment by mfranczy** [comment]
@rmohr true! Of course, I will take care of it.

**Comment by mfranczy** [comment]
Finally I created a PR https://github.com/kubevirt/user-guide/pull/131/files

**Comment by mfranczy** [comment]
PR is merged, we can close the issue (I don't have perms to do that)

**Comment by rmohr** [comment]
/close

Fixed in #131
