### ISSUE TITLE
Links under Volumes section are invalid

### ISSUE THREAD

**Issue by j-griffith** [kubevirt/user-guide#170]
In the disks-and-volumes guide there is a Volumes section with links to the different types of volumes (cloudInitNoCloud, etc); unfortunately clicking these links in the guide result in a 404 error.

**Comment by fabiand** [comment]
I think this was fixed

**Comment by j-griffith** [comment]
Yep, for historical purposes: [#171](https://github.com/kubevirt/user-guide/pull/171)
