### ISSUE TITLE
Metrics for OpenShift section don't seem to work

### ISSUE THREAD

**Issue by tripledes** [kubevirt/user-guide#172]
Section URL: https://kubevirt.io/user-guide/#/misc/monitoring?id=integrating-with-the-openshift-cluster-monitoring-operator

While the Kubernetes section works without any issue, the integration for OpenShift is not clear. I've done few tests with different settings and nothing really seems to work.

* Created the `ServiceMonitor` shown in the Kubernetes section within the `openshift-monitoring` namespace, I can see it being logged on the cluster-monitoring-operator logs (increasing verbosity) but nothing is being scrapped.

* Created the `ServiceMonitor` within the `kube-system` namespace, no improvement.

* Tried to create it again in the `openshift-monitoring` namespace but adding `namespaceSelector.matchNames` set to `kube-system`, doesn't work. I know that field is not required but just for the sake of getting it to work.

* I've added `openshift.io/cluster-monitoring: ""` label to the `selector.matchLabels` section, also added it to the service `kubevirt-prometheus-metrics` and even to the `virt-api` deployment. No improvement.

For all the tests, I never saw any KubeVirt related target being configured on the targets section of the prometheus UI. I'm currently out of options, but willing to test any suggestion.

I think it's worth noting the following from OCP docs [0]:

> Explicitly unsupported cases include:
>
>Creating additional ServiceMonitor objects in the openshift-monitoring namespace, thereby extending the targets the cluster monitoring Prometheus instance scrapes. This can cause collisions and load differences that cannot be accounted for, therefore the Prometheus setup can be unstable.
>
>Creating additional ConfigMap objects, that cause the cluster monitoring Prometheus instance to include additional alerting and recording rules. Note that this behavior is known to cause a breaking behavior if applied, as Prometheus 2.0 will ship with a new rule file syntax.

And also, from the cluster monitoring operator [1]:

>The deployed Prometheus Operator is intended to be used only for cluster-level monitoring. As such, the deployed Prometheus instance (prometheus-k8s) is responsible for monitoring and alerting on cluster and OpenShift components; it should not be extended to monitor user applications. Important: The Prometheus Operator managed by the Cluster Monitoring Operator will by default only look for ServiceMonitor resources in openshift-monitoring namespace.
>
>Users interested in leveraging Prometheus for application monitoring on OpenShift should consider using OLM to easily deploy a Prometheus Operator and setup new Prometheus instances to monitor and alert on their applications.

[0] [Prometheus cluster monitoring - supported configuration](https://docs.openshift.com/container-platform/3.11/install_config/prometheus_cluster_monitoring.html#supported-configuration)

[1] [Cluster monitoring operator - README](https://github.com/openshift/cluster-monitoring-operator#cluster-monitoring-operator)

**Comment by fabiand** [comment]
@fromanirh any idea?

**Comment by fromanirh** [comment]
hey there. @tripledes , which steps have you followed to set up the monitoring? just the kubevirt user guide?

**Comment by tripledes** [comment]
hey @fromanirh, so I deployed the cluster monitoring operator during installation of the OCP cluster and then used the KubeVirt user guide.

**Comment by fromanirh** [comment]
@tripledes ok, I need to review my notes. What you have here rings a bell, but can't pinpoint it. Due to upcoming holidays it could take a while, however.

**Comment by tripledes** [comment]
Thanks @fromanirh

**Comment by rmohr** [comment]
@fromanirh thanks for looking into that. Any conclusions so far?

**Comment by fromanirh** [comment]
We also had discussions in the mailing lists. Turns out that in openshift 3.11, additional ServiceMonitors are just ignored, and there is no workaround. AFAICT, we need to wait for openshift 4.0. At that point, a couple of new annotations should be sufficient to let the openshift prometheus operator pick up them.

**Comment by fromanirh** [comment]
for the sake of the completeness, there is a hack to pretend to be node_exporters and to plug in the existing openshift 3.11 configuration

https://github.com/fromanirh/kubevirt-metrics-collector#hack-deploy-on-kubevirt-running-on-okd-faking-node-exporter

But I don't think kubevirt should go in this direction, not even temporarily.
