### ISSUE TITLE
Changelog is not being updated

### ISSUE THREAD

**Issue by tripledes** [kubevirt/user-guide#214]
[Changelog](https://kubevirt.io/user-guide/docs/latest/release-notes/changelog.html) last entry is still 0.11.0.

**Comment by fabiand** [comment]
I suppose we should just add automation to run https://github.com/kubevirt/user-guide/blob/master/release-notes/update_changelog.sh regularly.

**Comment by fabiand** [comment]
@tripledes something you want to handle?

**Comment by tripledes** [comment]
Thanks @fabiand I'll have a look.
