### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by fedepaol** [kubevirt/user-guide#253]
While going through the docs, I found a couple of broken links, probably because the whole tree got reorganized:

##### architecture/virtualmachine.html :
- Link to "Run Strategies": `can be found in Run Strategies`
- Link to "Expose Services": `Exposing VirtualMachineInstance`

##### creating-virtual-machines/intro.html:
All the links at the bottom of the page:
- Link to volumes: `More information about persistent and ephemeral volumes`
- Link to graphical & serial access: `How to access a VirtualMachineInstance via console or vnc`
- Link to cloud init: `How to customize VirtualMachineInstances with cloud-init`

**Comment by iranzo** [comment]
This probably should have been closed with the merge of #254 , tagging @fabiand as he worked on the PR

**Comment by fabiand** [comment]
PRs to fix the links are welcome

**Comment by iranzo** [comment]
I meant that as the PR created by fedepaol was merged, this issue should be closed, isn't it?

**Comment by fabiand** [comment]
Oh Yes, please go ahead to close it

**Comment by iranzo** [comment]
I don't have permissions on this repo :-) but just stumbled upon this one :)

**Comment by fabiand** [comment]
Now you have!
