### ISSUE TITLE
We don't have docs based on release versions

### ISSUE THREAD

**Issue by rmohr** [kubevirt/user-guide#259]
/kind bug

It is hard to determine if specific features exist in a kubevirt version `X`.

**Comment by mazzystr** [comment]
/reopen

I'm reopening this issue.  We can get this feature with mkdocs.

**Comment by mazzystr** [comment]
Thanks bot.... this is correctly closed.  We don't want user-guide versioning at this point in the KubeVirt project per discussion at Weekly Meeting.
