### ISSUE TITLE
With the switch to asciidoc, search capabilities were removed

### ISSUE THREAD

**Issue by rmohr** [kubevirt/user-guide#297]
I use the user-guide very often to point people to examples and explanations. However, since the search box disappeared, even I can't find anything. I normally then go to the github repo and use the github search to find the page.

We should add a search box.

/kind enhancement

**Comment by iranzo** [comment]
Having search on static website requires some plugin. I do have that for my blog via a pelican extension that builds the 'search index' and is later accessed via AJAX. Alternativelly, we can consider readthedocs or some other service that takes care of that for us

**Comment by rmohr** [comment]
Whatever is necessary works for me. It was just there before we switched to asciidoc.

**Comment by iranzo** [comment]
@rmohr can someone give more details on 'WHY' the switch to asciidoc?  I was doing some quicksearch and if we had the docs in markdown it should be pretty easy move them to mkdocs which takes care of website generation, branding via themes, search box, disquss integration, even analytics

**Comment by iranzo** [comment]
I did a quick mockup with a 'non-verified' automated conversion to markdown here: https://kubevirt-user-guide-mockup.readthedocs.io/en/material/

This mockup is using 'readthedocs', but can be generated on travis via 'mkdocs' command and then pushed to github pages for hosting. Read the docs is also able to work out of a 'documentation' folder so even the docs could be in the same repo as the kubevirt code

It features the search using lunr.js, sitemap generation, automated menu based on folder hierarchy, ability to customize themes (see the little kubevirt icon), disquss integration for feedback like what we've on the web, etc.

Should we move this discussion on mailing list for discussion?

**Comment by iranzo** [comment]
Will be closed by #316
