### ISSUE TITLE
"Latest release notes" on v0.26.0

### ISSUE THREAD

**Issue by dhiller** [kubevirt/user-guide#342]
[Latest Release Notes](https://kubevirt.io/user-guide/latest_release_notes/) is not up to date. Maybe rather link to the releases page?

**Comment by codificat** [comment]
Right... there is a script to keep it up to date but it seems it stopped running with the migration to markdown. Certainly needs fixing

/remove-lifecycle-stale

**Comment by mazzystr** [comment]
Looks like we have it fixed.

@dhiller  Please confirm

**Comment by dhiller** [comment]
@mazzystr I'd expect that page to be in sync with the [releases page](https://github.com/kubevirt/kubevirt/releases/) from GitHub somehow. As this page has 0.35 and the latest is 0.38.1it seems like it's not.

**Comment by mazzystr** [comment]
Do you want me to run the script manually to catch the markdown up to
current?  After that we can verify the script will run as part of the
release script.

**Comment by dhiller** [comment]
> Do you want me to run the script manually to catch the markdown up to current? After that we can verify the script will run as part of the release script.

Maybe just integrate that script call into the make target that builds the site? This way it's handled automatically? I figure that is not done yet?

**Comment by dhiller** [comment]
Also we can then just see whether it works in the PR.
