### ISSUE TITLE
avoid broken links

### ISSUE THREAD

**Issue by dankenigsberg** [kubevirt/user-guide#343]
https://kubevirt.io/user-guide/#/templates/templates has two links. One is internal https://kubevirt.io/user-guide/#/installation/README ; the other is external https://docs.openshift.org/latest/dev_guide/templates.html . Both of them are broken.

We should continuously find and correct broken links in this repository. Internal ones can be avoided by a static analyzer; external ones require periodic crawling.

/cc @brianredbeard

**Comment by codificat** [comment]
Related: kubevirt/kubevirt.github.io#576

**Comment by mazzystr** [comment]
@dankenigsberg I'm pretty sure we have this link fixed.  We're getting clean `make check_links`

re link checking ... we just established manual link checking with the user-guide migration.  We're going to integrate into kubebot CI/CD shortly.  :)

**Comment by mazzystr** [comment]
@eifrach tagged

**Comment by dankenigsberg** [comment]
I was going over the links in https://kubevirt.io/user-guide/#/templates/templates ; at least one is still broken.

**Comment by sradco** [comment]
https://kubevirt.io/user-guide/#developer -  Start contributing: Appendix/Contributing is broken
 Also here https://github.com/kubevirt/user-guide#developer

**Comment by mazzystr** [comment]
@dankenigsberg `at least one` is vaguebooking.  ;)  `#` and `id=`'s are not valid user-guide urls.  Those come from the old docsify markdown engine.  The following is the only correct use of a `#`:
```
https://kubevirt.io/user-guide/welcome/#try-it-out
                                       ^---- # selector pertains to the header in markdown
```
You may have to clear your browser cache to get to the new mkdocs javascript.

**Comment by mazzystr** [comment]
@sradco re Appendix/Contributing ... That link was repaired on on Feb 23.  Blame is [here](https://github.com/kubevirt/user-guide/blame/master/docs/welcome.md#L20).  You may need to do a browser refresh.

re https://github.com/kubevirt/user-guide#developer... Sigh.  _Somebody_ (me) did a bad copy and paste job. ;)

**Comment by dankenigsberg** [comment]
I just opened https://kubevirt.io/user-guide/#/templates/templates in a fresh incognito browser. It still has the broken Appendix/Contributing link.

@mazzystr please fix all links leading to 404. When you're done, let me know..

**Comment by mazzystr** [comment]
Issue re Welcome page broken link is [here](https://github.com/kubevirt/user-guide/issues/424)

**Comment by dankenigsberg** [comment]
> Issue re Welcome page broken link is here

I'm not aware of any other broken link; I noticed none in https://kubevirt.io/user-guide/virtual_machines/templates . Are you aware of any other broken link? If not, you may close this issue.

**Comment by mazzystr** [comment]
virtual_machines/templates page is clean to me and according to tools.  `Clean to me` means greping the file for links then manually curling them. Do what ya gotta go sometimes... ;-)

I will close this Issue then.  Thanks!
