### ISSUE TITLE
Fix KubeVirt architecture section

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/user-guide#348]
/kind bug

The current [architecture](https://kubevirt.io/user-guide/architecture) page in user-guide does not actually describe the KubeVirt architecture.  Please rebuild this doc. 

Update: Architecture doc is [here|https://github.com/kubevirt/kubevirt/blob/master/docs/architecture.md].  This story just becomes a matter of fixing the web page link which is significantly easier.

**Comment by ansijain** [comment]
@mazzystr I have been looking into this.
Do I need to add external link [here](https://github.com/kubevirt/user-guide/blob/master/docs/.pages) ?
or should I add https://github.com/kubevirt/kubevirt/blob/master/docs/architecture.md in user-guide repo?
Or any other way please guide
