### ISSUE TITLE
Include documentation on uninstallation of Kubevirt

### ISSUE THREAD

**Issue by brianredbeard** [kubevirt/user-guide#367]
As a user, I attempted to use Kubevirt/CNV.

After testing things out, I attempted to delete the various resources.

Unfortunately, this introduced a race condition due to resource dependencies around the `kubevirt-validator.kubevirt.io` webhook.

Now, I have resources across the cluster which cannot be deleted due to the missing webhook.

This was discovered because the `openshift-cnv` namespace has been in state "Terminating" for ~45 days.

```
$ oc -n  openshift-cnv get all
NAME                                              AGE   PHASE
cdi.cdi.kubevirt.io/cdi-kubevirt-hyperconverged   94d   Deployed

NAME                                                     AGE
hyperconverged.hco.kubevirt.io/kubevirt-hyperconverged   94d

NAME                                                    AGE   PHASE
kubevirt.kubevirt.io/kubevirt-kubevirt-hyperconverged   94d   Deployed
$ oc -n  openshift-cnv delete hyperconverged.hco.kubevirt.io/kubevirt-hyperconverged 
hyperconverged.hco.kubevirt.io "kubevirt-hyperconverged" deleted    

# command then hangs endlessly
```

In a second terminal, while the previous command is hanging:
```
$ oc -n  openshift-cnv delete kubevirt.kubevirt.io/kubevirt-kubevirt-hyperconverged
Error from server (InternalError): Internal error occurred: failed calling webhook "kubevirt-validator.kubevirt.io": Post https://kubevirt-operator-webhook.openshift-cnv.svc:443/kubevirt-validate-delete?timeout=30s: service "kubevirt-operator-webhook" not found
```

After running both of these commands (and receiving the notice from the deletion of the first resource - `hyperconverged.hco.kubevirt.io/kubevirt-hyperconverged`) and running the same `oc -n  openshift-cnv get all` in a new terminal shows the same output:

```
$ oc -n  openshift-cnv get all
NAME                                              AGE   PHASE
cdi.cdi.kubevirt.io/cdi-kubevirt-hyperconverged   94d   Deployed

NAME                                                     AGE
hyperconverged.hco.kubevirt.io/kubevirt-hyperconverged   94d

NAME                                                    AGE   PHASE
kubevirt.kubevirt.io/kubevirt-kubevirt-hyperconverged   94d   Deployed
```

**Comment by fabiand** [comment]
This looks like a bug related to a product, I'd kindly ask you to file the ticket at the vendor's bug tracker.

However, it also looks like this is an issues as also seen in #2605 and kubernetes/kubernetes#60807.
The more complex Kubernetes extensions and operators become, the more challenging it is to maintain old paterns - like removing a namespace in order to achieve an uninstallation.

We are looking at fixing this and enabling "the common behavior". In the meantime the procedure - especially in the case of your product - is to remove the HCO CR, unsubscribe the operator - this should remove all traces from your system.

**Comment by mazzystr** [comment]
@brianredbeard  Can you try the procedure detailed [here](https://kubevirt.io/user-guide/#/installation/updating-and-deleting-installs)?

Let us know if it still fails.  We're going through a user-guide content revaluation as we speak.  We will note that the page needs refreshing if it has gone stale.

**Comment by brianredbeard** [comment]
@mazzystr alas I cannot.  In the end it was causing instability issues with cluster upgrades (specifically around the webhook admission controller blocking upgrades) and a little over a week ago a week ago.  As there is now some content around uninstalling Kubevirt, I'll close out this issue out and in the event that subsequent problems occur it can be re-visited.
