### ISSUE TITLE
Automation needed to ensure ascii only characters in markdown

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/user-guide#405]
HTMLproofer link checker cannot handle utf-8 characters.  The app ends up crashing.

We need automation to ensure no non-ascii (utf-8) characters make it in to the repo.

**Comment by mazzystr** [comment]
@sfxworks This one is for you

**Comment by sfxworks** [comment]
FYI continuing work on this this week. Work has had me busy so I apologize.

**Comment by sfxworks** [comment]
Yikes! Sorry I've been working a ton on job related work. I'll see if I can't set aside time in the next 30d. Very sorry all!
