### ISSUE TITLE
Add "make check_spelling check_links" to CI

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/user-guide#414]
See Prow settings in kubevirt/project-infra

Ask @dhiller if you have questions

**Comment by phoracek** [comment]
/remove-lifecycle frozen

Link check is missing too: https://github.com/kubevirt/user-guide/pull/656

**Comment by phoracek** [comment]
I don't know about prow support, but we do use a link checker through prow for kubevirt.github.io: https://github.com/kubevirt/project-infra/blob/main/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt.github.io/kubevirt-github-io-presubmits.yaml#L3 The target itself is defined under the kubevirt.github.io repo.

We could create a similar prow lane for this repo, calling `make check_links check_spelling`.
