### ISSUE TITLE
Add architecture diagram to user-guide

### ISSUE THREAD

**Issue by ansijain** [kubevirt/user-guide#423]
Addition of https://github.com/kubevirt/kubevirt/blob/master/docs/architecture.md to user-guide[https://github.com/kubevirt/user-guide/blob/master/docs/architecture.md] for better understanding of kubevirt components

**Comment by mazzystr** [comment]
@ansijain Would you mind if I closed this issue as duplicate of [issues/348](https://github.com/kubevirt/user-guide/issues/348)?

**Comment by ansijain** [comment]
Yes.
Sorry I didn't noticed it exists

**Comment by mazzystr** [comment]
Cool, Thanks!  Duplicate label added.  Closing...
