### ISSUE TITLE
More Information Required for hugepages.md 

### ISSUE THREAD

**Issue by ansijain** [kubevirt/user-guide#431]
More information could be added to https://github.com/kubevirt/user-guide/edit/master/docs/operations/hugepages.md
such as examples, limitations (If any)

**Comment by mazzystr** [comment]
@ansijain my test box only has 16 GiB of memory.  Do you have a box with more to test and update the page?

**Comment by ansijain** [comment]
@mazzystr I was expecting more details on this page Similar to https://kubevirt.io/2018/Kubevirt-v0.7.0.html blog

**Comment by cwilkers** [comment]
I may be able to help here. I'll add it to my list.
