### ISSUE TITLE
link is broken to CONTRIBUTING 

### ISSUE THREAD

**Issue by eifrach** [kubevirt/user-guide#433]
In the following  page there is a link to "CONTRIBUTING"  that is not working

https://github.com/kubevirt/user-guide/blob/master/CONTRIBUTING.md

**Comment by ansijain** [comment]
@eifrach seems that page is under construction. 
contributing guide is redirecting to https://github.com/kubevirt/community/blob/master/contributors/contributing.md

**Comment by mazzystr** [comment]
New issue opened in Community to do the real GUIDELINES work.  Link is [here](https://github.com/kubevirt/community/issues/103).

Since the link works correctly.  Let's close this issue.

**Comment by eifrach** [comment]
closing this issue
