### ISSUE TITLE
Can't get it to run on local with: '/srv/mkdocs.yml': Permission denied

### ISSUE THREAD

**Issue by borod108** [kubevirt/user-guide#476]
Following the instructions from the readme, after I make build_img and then try to make run the container immidiatly exists with an error.
```
(base) ➜  user-guide git:(imporve_sysprep_doc) ✗ make run    

Makefile: Stop site
podman rm -f userguide 2> /dev/null; echo
048d7d12f9f9aef5c74e122980f96551d02e7d88d98d45938dc26b7b76739137

Makefile: Run site
podman run \
                        -d \
                        --name userguide \
                        -p 8000:8000 \
                        -v /home/bod108/work/user-guide:/srv:ro \
                        -v /dev/null:/srv/Gemfile.lock:rw \
                        --mount type=tmpfs,destination=/srv/site \
                        localhost/kubevirt-user-guide \
                        /bin/bash -c "mkdocs build -f /srv/mkdocs.yml && mkdocs serve -f /srv/mkdocs.yml -a 0.0.0.0:8000"
24ae628e36132c5b9b686f4d39f0bed1ffdf1da5211447271174803f0526612c

Makefile: Server now running at [https://localhost:8000]

(base) ➜  user-guide git:(imporve_sysprep_doc) ✗ podman ps -a
CONTAINER ID  IMAGE                          COMMAND               CREATED        STATUS                    PORTS                   NAMES
24ae628e3613  localhost/kubevirt-user-guide  /bin/bash -c mkdo...  3 seconds ago  Exited (2) 3 seconds ago  0.0.0.0:8000->8000/tcp  userguide
(base) ➜  user-guide git:(imporve_sysprep_doc) ✗ podman logs -t 24ae628e3613
2021-08-22T14:24:08.234290133+03:00 Usage: mkdocs build [OPTIONS]
2021-08-22T14:24:08.234290133+03:00 Try 'mkdocs build -h' for help.
2021-08-22T14:24:08.234290133+03:00 
2021-08-22T14:24:08.234403231+03:00 Error: Invalid value for '-f' / '--config-file': '/srv/mkdocs.yml': Permission denied
```

**Comment by borod108** [comment]
@mazzystr I am not sure who to ping about this, perhaps you know?

**Comment by mazzystr** [comment]
Can you tell me about your environment?  Are you running this on Linux on metal or is it Linux on virtual machine on something?  Do you run with SELinux enabled?

**Comment by cwilkers** [comment]
+1 on the SELINUX enabled, this message looks just like the ones I get if I don't set that environment variable.

    export SELINUX_ENABLED=True

and try the same make command again.

**Comment by borod108** [comment]
@mazzystr @cwilkers thank you, export SELINUX_ENABLED=True did it!
Even going back to the readme after knowing the solution I can say I would not have figured this out :/
I would consider adding something to the readme to make it clearer for people like me...

Thank you very much for your help!

**Comment by cwilkers** [comment]
I did add this https://github.com/kubevirt/kubevirt.github.io/pull/789 so hopefully it doesn't bite as many people from here out.

**Comment by borod108** [comment]
@cwilkers awesome! thank you!

**Comment by mazzystr** [comment]
@borod108 Are you cool with closing this issue?

**Comment by borod108** [comment]
sure, thank you!
