### ISSUE TITLE
Device Role Tagging VM spec snippet is wrong

### ISSUE THREAD

**Issue by ormergi** [kubevirt/user-guide#512]
The VM spec on the example of [[1]](https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#device-role-tagging)
is wrong.
The `tag` should be part of each device object instead on the `domain` level.
It seems like interpretation problem of the markdown file since it looks right on the file itself [[2]](https://github.com/kubevirt/user-guide/blob/master/docs/virtual_machines/startup_scripts.md#device-role-tagging)

**Comment by cwilkers** [comment]
It looks like the referenced PR should have closed this issue. I will close it now, if that's in error, please feel free to reopen.
