### ISSUE TITLE
Resources Requests and Limits seems to have the CPU request and limit backwards

### ISSUE THREAD

**Issue by cbf123** [kubevirt/user-guide#519]
In user-guide/docs/virtual_machines/virtual_hardware.md under "Resources Requests and Limits" the example shown has a request of 2 CPUs and a limit of 1 CPU.  This seems backwards since in the normal case the limit would be higher than the request.

**Comment by cwilkers** [comment]
I believe this is fixed by https://github.com/kubevirt/user-guide/pull/520
