### ISSUE TITLE
Add "virtctl ssh" to the documentation 

### ISSUE THREAD

**Issue by isaacdorfman** [kubevirt/user-guide#537]
This should be placed inside the part of the docs about connecting to a vm:
https://kubevirt.io/user-guide/virtual_machines/accessing_virtual_machines/#ssh-access

**Comment by cwilkers** [comment]
Thank you for raising this issue, would you be interested in creating a PR in this repository to address it?

**Comment by KiranSatyaRaj** [comment]
@cwilkers should ssh access be a part of ToC than only being visible when accessing VM section collapses?

**Comment by cwilkers** [comment]
Accessing a VM in general should be in the ToC, maybe not each individual method. (I write this not having first checked if it is already there...)

**Comment by cwilkers** [comment]
I just checked the current state, and I like how it is referenced in the ToC and in the accessing virtual machines page. I agree, this issue is completed.
