### ISSUE TITLE
Need to update version for Kubevirt installation in Kubernetes

### ISSUE THREAD

**Issue by oshi36** [kubevirt/user-guide#543]
In the user guide, the instructions to [install Kubevirt in Kubernetes](https://kubevirt.io/user-guide/operations/installation/#installing-kubevirt-on-kubernetes) specify an outdated version(v0.35.0) as it is not compatible with latest K8s releases. 
The documentation should have the latest version of kubevirt (v0.53.1)

**Comment by aburdenthehand** [comment]
@oshi36 Thanks for raising this issue, and apologies for not seeing it earlier. I've opened #546 to address this.

**Comment by oshi36** [comment]
Thank you @aburdenthehand for addressing the issue.
