### ISSUE TITLE
Rename 'latest release notes' to something more accurate

### ISSUE THREAD

**Issue by aburdenthehand** [kubevirt/user-guide#547]
As discussed in #546, the current naming scheme could be improved. 
My suggestion is the prosaic "KubeVirt release notes" but happy for alternatives. 

This involves updating the following files within the kubevirt/user-guide repo:
 - docs/.pages
 - update_changelog.sh
 - latest_release_notes.md (within the file and filename)
 
Other things worth considering:
- Is latest_release_notes.md referenced in any other repos?
- Do we need to think about redirects (since changing url)?

**Comment by cwilkers** [comment]
Is this resolved by #546 or does there need to be automation added to keep things current?
