### ISSUE TITLE
Secure boot not documented

### ISSUE THREAD

**Issue by ninjacoder80** [kubevirt/user-guide#548]
There is no documentation for secure boot even though it was implemented in PR3529 in Kubevirt release v0.31.0 

PR3529
https://github.com/kubevirt/kubevirt/pull/3529

Release notes 
https://kubevirt.io/user-guide/latest_release_notes/#v0310

API reference
http://kubevirt.io/api-reference/v0.31.0/definitions.html

**Comment by cwilkers** [comment]
@jean-edouard @stu-gott Could you please take a look?

**Comment by jean-edouard** [comment]
Will do. There's not much to say about it but I'll give it a shot
