### ISSUE TITLE
Add Quickstart tutorials

### ISSUE THREAD

**Issue by aburdenthehand** [kubevirt/user-guide#556]
The user guide is lacking quickstart/tutorial material to help new users beyond initial installation. 

After discussion with new users and the CNCF Technical Docs team, this kind of material would be critical in helping new users become accommodated with using KubeVirt, and would be a helpful jumping off point to learning core concepts. 

As I understand it, we used to have [Katacoda material ](https://github.com/kubevirt/katacoda-scenarios)that covered this, unfortunately katacoda is now closed as a free public resource. We might be able to use some of the content here though

A rough idea of what this might look like:
1) Basic quickstart:
- Start with K8s cluster; install KubeVirt
- Either create a storageclass or point to information about storageclass
- networking basics - default pod and external networks
- Install virtctl
- Create a VM 
- Start VM
- SSH (or console?) into VM
- Shut down VM

2) Importing a VM
- Start with K8s cluster; install KubeVirt
- Install virtctl
- Install CDI
- Either create a storageclass or point to information about storageclass
- networking basics - default pod and external networks
- Import a VM- Start VM
- SSH (or console?) into VM
- Shut down VM
- Start VM
- SSH (or console?) into VM
- Shut down VM

These examples are not definitive and would definitely benefit from input from others.

**Comment by cwilkers** [comment]
If it makes sense, I can try to quickly get the intro material up and running on Killercoda. There are still usability issues for CDI and migration there due to the drastically limited resources compared to Katacoda.

**Comment by cwilkers** [comment]
Also, I'm not sure why it was originally divided this way, but the quickstart tutorials are in the https://github.com/kubevirt/kubevirt.github.io side of the website. Currently there are tutorials for install, CDI, live migration, and upgrade of KubeVirt at https://kubevirt.io/labs/

**Comment by aburdenthehand** [comment]
@cwilkers Yeah, that is a bit interesting. And those labs aren't directly linked (as far as I can tell, anyway) from the user guide - you have to click on one of the quickstart links before you see they exist. 

I'm going to say that's a different issue than the one presented here, however, and close this issue. 

Thanks to @cwilkers and the team at Killercoda, we have KubeVirt scenarios again: https://killercoda.com/kubevirt
These can be found on the kubevirt.io splashpage and in the user guide: https://kubevirt.io/user-guide/#try-it-out
And there are also labs linked in cwilkers previous comment (and I'll raise another issue to cover how we can make these more obvious in the user guide)
