### ISSUE TITLE
Link to the kubevirt labs from docs

### ISSUE THREAD

**Issue by aburdenthehand** [kubevirt/user-guide#587]
We have 4 labs (https://kubevirt.io/labs/) hosted on the website that provide useful context for new users and guide them through a few key scenarios, but they don't seem to be linked from the docs at all. They only seem visible if you start on the website and click the 'Labs' tab.

It would be great if we could additionally link to the labs from the docs, probably here: https://kubevirt.io/user-guide/#try-it-out

**Comment by KiranSatyaRaj** [comment]
I would like to start working on this issue @aburdenthehand , so should I create the lab section on the welcome page, if not please describe how it's visibility supposed to be?

**Comment by aburdenthehand** [comment]
@KiranSatyaRaj Yes, I think that's a good approach. So because there's no base 'lab' url we can link to, we should list the four links. It will be very similar to the 'Try it out' section, with a list of the four labs.
ie
KubeVirt Labs

Use Kubevirt: https://kubevirt.io/labs/kubernetes/lab1.html
Experiment with KubeVirt: https://kubevirt.io/labs/kubernetes/lab2.html
etc
