### ISSUE TITLE
Make quickstart guides more visible in the docs ToC

### ISSUE THREAD

**Issue by aburdenthehand** [kubevirt/user-guide#588]
We currently have 4 quickstart guides which are linked to from the website splash page and in the docs here: https://kubevirt.io/user-guide/#try-it-out
These are visible when you navigate directly to https://kubevirt.io/user-guide or from the splash page, but the 'Welcome' section of the Table of Contents, in which these are nested, collapses if you are viewing any other part of the docs. This means that the quickstart content is not immediately obvious from the ToC unless you're already looking at that page.

I think it would be useful to move the quickstart guides to the same level as the Welcome, Architecture, and KubeVirt release notes pages so that the quickstarts are always visible in the ToC. 
I don't think we need to remove the #try-it-out section from the Welcome page, as it still makes sense to be visible there as well (and means we don't need redirects)

Related: we also have 4 labs that should be included in the quickstarts but these are not currently linked to in docs (see #587)

**Comment by KiranSatyaRaj** [comment]
I can work on this, but I'm unable to find the html for ToC @aburdenthehand, I need your help, I can take it from there onwards.

**Comment by aburdenthehand** [comment]
Hi Kiran!
I believe the markdown ToC is `docs/.pages` 
You'll also want to create the markdown page for the quickstarts in the same directory.
Thanks for helping out!

**Comment by KiranSatyaRaj** [comment]
> Hi Kiran! I believe the markdown ToC is `docs/.pages` You'll also want to create the markdown page for the quickstarts in the same directory. Thanks for helping out!

Got it!! Thank you so much, I will take it from here onwards.

**Comment by KiranSatyaRaj** [comment]
Hey @aburdenthehand, these are the changes I made as you can see I added the quickstarts section, well it's not complete but I can do it, so can you assign this issue to me ?
[Screenshot from 2022-10-19 19-53-09.pdf](https://github.com/kubevirt/user-guide/files/9821457/Screenshot.from.2022-10-19.19-53-09.pdf)

**Comment by KiranSatyaRaj** [comment]
Hey @aburdenthehand, I made the changes and checked it locally, should It view a try it out and labs section when it collapses?

**Comment by KiranSatyaRaj** [comment]
> Good stuff @KiranSatyaRaj Once collapsed there should be a Welcome, Architecture, Quickstarts, and KubeVirt Release Notes (I think that's the order that makes the most sense). I think 'Quickstarts' for the ToC because it's broadly recognisable - but we can leave the 'Try it out' subsection nested in 'Welcome' as it is. Re: the labs. You can add them here, or you can separate the two issues and create a separate PR that adds the Labs links to the 'Try it out' subsection and the 'Quickstarts' section. Personally I would open a second PR because, while related, they're tackling different issues.
> 
> Hope that helps!

I have a few more stuff to be cleared out, can we discuss them on slack, if that's okay?

**Comment by aburdenthehand** [comment]
Yep, you can find me on Kubernetes slack.

**Comment by KiranSatyaRaj** [comment]
#603 
Hey @aburdenthehand, I made the pull request and referenced it here, kindly go through it and please suggest me what should be the introductory line for it and I'll include them.

**Comment by KiranSatyaRaj** [comment]
#605 made the pull request with the desired changes, please go through it @aburdenthehand
