### ISSUE TITLE
Add context that user needs to resize partitions if not using cloudinit or sysprep

### ISSUE THREAD

**Issue by aburdenthehand** [kubevirt/user-guide#593]
Currently CDI and KubeVirt resize the virtual disks but not partitions on those disks. This is because we don't know which partition to resize (in case there are multiple), and there is currently no mechanism for the user to specify. 
As such, the recommendation is to manually resize partition/s based on the guest OS. 

While this is predominately covered by using either cloudinit or sysprep to resize the partition during startup, it would be good if we included this context for users so that they know why partition size does not match disk size.

This is likely going to be a short note in one or both of the following files:
`operations/containerized_data_importer.md`
`virtual_machines/disks_and_volumes.md`

@awels - Does this accurately cover the scenario?

**Comment by awels** [comment]
I just checked both locations and neither really mention resizing disks. This particular piece of information should go together with the resizing documentation. There are 2 places this can happen:
1. When you clone a disk with CDI, you can make the target larger than the source. This will increase the disk size compared to the source.
2. When you resize a PVC containing a disk. You need a CSI driver capable of resizing, and once the PVC is resized, on the first start of the VM after the resize, the disk will be resized to match the PVC.

I am not sure if any of this information is in the documentation at this point, a quick search of the documentation didn't bring this up (its in docs in the cdi repo though)
