### ISSUE TITLE
Web console wizard tables malformatted

### ISSUE THREAD

**Issue by aburdenthehand** [kubevirt/user-guide#594]
Looks like the two first tables in the web console have contents in the wrong cells:
https://kubevirt.io/user-guide/web_console/#virtual-machine-template-wizard-fields
https://kubevirt.io/user-guide/web_console/#virtual-machine-wizard-fields

To fix, I think we need to change the following:
1. 'PXE', 'URL', and 'Container' should all be in the 'Parameter' column of 'Provision Source', with associated descriptions in the third column. 
2. 'generic' and 'highperformance' should be in the 'Parameter' column of ' Workload Profile', with associated description in the third column.
3. Specific only to the Virtual Machine Template Wizard Fields table: I think we can remove the first 'Provision Source' row (seems to be confused with the second 'Provision Source' row) and the 'Template' row (as I don't think you can create a template using a template).

File to update: web_console.md

Additional quests: Are we able to make the second column (Parameter) thinner? It is currently pushing the Description column off-screen. 
Are these fields still valid? I have a feeling these are from a much earlier version of KubeVirt.

**Comment by adithyaakrishna** [comment]
Can I take this up?

**Comment by aburdenthehand** [comment]
@adithyaakrishna Absolutely! Thanks for jumping onto it :D

**Comment by aburdenthehand** [comment]
@adithyaakrishna Oh, you know what. If #653 is accepted this will be redundant

**Comment by phoracek** [comment]
The console documentation was removed from the user-guide: https://github.com/kubevirt/user-guide/pull/653
