### ISSUE TITLE
Netlify: select a new build image

### ISSUE THREAD

**Issue by nate-double-u** [kubevirt/user-guide#596]
Related: https://github.com/kubevirt/kubevirt.github.io/issues/873

Notice from Netlify
> After November 15, 2022, builds for this site will fail unless you [update the build image](https://app.netlify.com/sites/cloudevents-io/settings/deploys#build-image-selection).

**Comment by aburdenthehand** [comment]
The build image has been updated for the user-guide and after a couple of necessary changes we have confirmed that the new image builds successfully.
