### ISSUE TITLE
user-guide postsubmit failed

### ISSUE THREAD

**Issue by dhiller** [kubevirt/user-guide#623]
Seems there's something wrong with the python version in the build image:

```
Cloning into 'user-guide-gh-pages'...
Makefile: Build mkdocs site(B
which python[3](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-user-guide-main-build-and-push-to-gh-pages/1590988274984292352#1:build-log.txt%3A3).8
make: *** [Makefile:11[5](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-user-guide-main-build-and-push-to-gh-pages/1590988274984292352#1:build-log.txt%3A5): build] Error 1
```
([source](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-user-guide-main-build-and-push-to-gh-pages/1590988274984292352))

**Comment by cwilkers** [comment]
Yeah, we had to update to the latest netlify container to keep the site building. I'll fast track the work I did in kubevirt.github.io to try to get user-guide's container image updated.
