### ISSUE TITLE
Disk Device Cache mode update

### ISSUE THREAD

**Issue by ChandonPierre** [kubevirt/user-guide#627]
Support for `writeback` caching was added in this PR: https://github.com/kubevirt/kubevirt/pull/6968

However the current docs do not reflect this: https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#disk-device-cache

**Comment by cwilkers** [comment]
Hi @ChandonPierre , thanks for raising the issue! Would you like to volunteer a PR to update the documentation?

**Comment by adithyaakrishna** [comment]
@cwilkers I would like to work on this, could you please give me a few more details regarding what I should add?

**Comment by cwilkers** [comment]
Hi @adithyaakrishna thank you for your interest! I would suggest you start by checking the disks_and_volumes link above, and using the links at the top of the page to find the original source page on our user-guide GitHub repo. Assuming you are familiar with the writeback caching feature from PR 6968 mentioned above, you can create a PR to add the relevant feature to that page.
