### ISSUE TITLE
Unable to build user-guide locally

### ISSUE THREAD

**Issue by jcanocan** [kubevirt/user-guide#638]
Hi all,

I have been trying to build and run the project locally in Fedora 37. However, the following error appears:

```sh
$ podman logs userguide
Usage: mkdocs build [OPTIONS]
Try 'mkdocs build -h' for help.

Error: Invalid value for '-f' / '--config-file': '/srv': Permission denied
```
If you run the `podman run` command adding the `--security-opt label=disable` option, i.e. turning off label separation for the container, the website is deployed without any issues.
Also, if you relabel the whole directory using:

```sh
sudo chcon -R -t container_file_t user-guide/
```
It works. Therefore, it's a SELinux problem.
The question is how to fix this in the Makefile to work out-of-the-box by running `make build_img && make run`.

Thanks!

**Comment by cwilkers** [comment]
Are you getting this error with the SELINUX_ENABLED=True ?

**Comment by cwilkers** [comment]
Could you try again now #634 is merged?

**Comment by jcanocan** [comment]
Yes. It is working now. Many thanks! :)

**Comment by jcanocan** [comment]
Before #634 it worked using SELINUX_ENABLED=True. 
After #634 it is still working using SELINUX_ENABLED=True. Without the SELINUX_ENABLED, I'm still getting the same error. 
Many thanks! :)

**Comment by cwilkers** [comment]
This catches people often enough that it might be worth adding logic to the Makefile to determine if SELinux is enabled, but I am not sure how to best do that in a distro-friendly way (and in a Makefile). Ideas or PRs would be welcome there.

It may be a good idea to close this issue and open a new one as an RFE. What do you think?

**Comment by jcanocan** [comment]
I agree.
