### ISSUE TITLE
Redirect users to Contributing Guide Directly

### ISSUE THREAD

**Issue by adithyaakrishna** [kubevirt/user-guide#659]
**Description:**

Instead of directing users from https://github.com/kubevirt/user-guide/blob/main/CONTRIBUTING.md to https://github.com/kubevirt/community/blob/main/contributors/contributing.md and from there to https://kubevirt.io/user-guide/appendix/contributing/ - ( which is currently giving a 404 Error. I have fixed the link and created a PR for the same here, https://github.com/kubevirt/community/pull/214 ), how about we do it directly from the user-guide to https://kubevirt.io/user-guide/contributing/

Another option, we can redirect them directly to https://github.com/kubevirt/kubevirt/blob/main/CONTRIBUTING.md

So the users instead of traversing through the maze, will be taken directly from user-guide to https://kubevirt.io/user-guide/contributing/ 

Fixed by  #710

**Comment by cwilkers** [comment]
I agree, we should point to a centralized start page for new contributors, and it looks like that is currently https://kubevirt.io/user-guide/contributing/.

For repos that have their own guide (such as kubevirt and user-guide) the individual repo's README.md should point both to the website contributing page and to the local repo contribution guide. The website guide should have a section that branches to all these individual guides in a clear way so potential contributors can get the boilerplate items like CNCF policy, KubeVirt code of conduct, and DCO signoffs in a central place before getting to more specific work.

**Comment by aburdenthehand** [comment]
@adithyaakrishna Were you still interested in working on this?
To add to Chandler's suggestion, I think pointing to our [governance](https://github.com/kubevirt/community/blob/main/GOVERNANCE.md) and [membership policy](https://github.com/kubevirt/community/blob/main/membership_policy.md) documents would be really helpful as well. 
I've also created #701 to include a simple style/convention guide to the user-guide contrib page. 
All this needn't all be captured in a single PR, but perhaps we can make use of the Projects function of github and track this work there.

**Comment by cwilkers** [comment]
I think this was fixed in #710, we can close now.
