### ISSUE TITLE
User guide contributor guide

### ISSUE THREAD

**Issue by aburdenthehand** [kubevirt/user-guide#701]
It would be good to update our contributor guide for KubeVirt docs to capture some of the conventions. The current guidelines are very high level, and the repo readme focuses on test builds - all good stuff, but some lower level guidance for things like basic structure, style, and conventions like version support and when to deprecate content etc would be useful.

Links: 
https://kubevirt.io/user-guide/contributing/ (currently an issue already open about the multiple redirects to get to this page: #659 )
https://github.com/kubevirt/user-guide

**Comment by pragatisaikia** [comment]
May I know exactly what changes are we suppose to make to which files.

**Comment by aburdenthehand** [comment]
Hi @pragatisaikia - thank you for your enthusiasm and patience!
I think we will want to create a new file, and I think the best place for it will be in the root directory of the user-guide repo.
We can call it 'docs-guidelines.md'

To start with, we can copy a couple of the relevant points from the [blog guidelines](https://github.com/kubevirt/kubevirt.github.io/blob/main/GUIDELINES.md), namely:
- Follow [Kramdown Quick Reference](https://kramdown.gettalong.org/quickref.html) for syntax reference
- Split the contents in sections using the different levels of headers that Markdown offers
  - Keep in mind that once rendered, the title you set in the Front Matter data will use `H1`, so start your sections from `H2`
- [Code blocks](https://kramdown.gettalong.org/syntax.html#code-blocks), use them for:
  - code snippets
  - file contents
  - console commands
  - ...
  - Use the proper tag to let the renderer what type of contents your including in the block for syntax highlighting
 - Don't include a command prompt in console commands, to simplify copy/paste.
 
 We can postpone the version support for the moment as it is still being discussed. 
 Thanks!

**Comment by UncleWeeds** [comment]
I would like to work on this

**Comment by aburdenthehand** [comment]
@pragatisaikia - are you still interested in working on this? If not, I will assign @UncleWeeds

**Comment by pragatisaikia** [comment]
> @pragatisaikia - are you still interested in working on this? If not, I will assign @UncleWeeds

I'm looking into it. If not resolved, I'll mention asap.

**Comment by UncleWeeds** [comment]
@aburdenthehand it's been a while can I start working on this

**Comment by pragatisaikia** [comment]
> @aburdenthehand it's been a while can I start working on this 

I think you can work on this

**Comment by chuot803** [comment]
Hi! My group and I from UT Austin are interested on working on this :) I was wondering what work has already been done towards this issue and what else we would need to add. Thanks!

**Comment by aburdenthehand** [comment]
Hello @chuot803 - I'm not aware of any movement on this. From my point of view you are very welcome to work on this.
 @UncleWeeds ?

**Comment by tbunch1** [comment]
Hi, I'm working with Lindsey. You mentioned adding information about when to deprecate content. When should that be? Or where can I find information on things like that?

**Comment by aburdenthehand** [comment]
@tbunch1 - Great question. We can use our [support matrix](https://github.com/kubevirt/sig-release/blob/main/releases/k8s-support-matrix.md) to guide us here.
Once it passes 3 K8s versions out of date (ie, if it's no longer present on our matrix at all) then we can safely remove it. This gives folks ~1 year out of support.
