### ISSUE TITLE
Hook sidecar documentation on user guide

### ISSUE THREAD

**Issue by dharmit** [kubevirt/user-guide#726]
https://github.com/kubevirt/kubevirt/pull/10479 adds support to run scripts as a part of hook sidecar. The PR adds docs which are available on kubevirt repo, but nothing about sidecars exists on user guide (at least I couldn't find anything around using it). If it makes sense, I'd like to add documentation for this on the user-guide since, I think, it's something that should be in the user facing docs.

If this sounds reasonable, I'd need some help figuring out which section of user guide this would fit in - a separate section of its own under "Operations" tab, or under something existing?

**Comment by dharmit** [comment]
@aburdenthehand @cwilkers @victortoso pinging to know your thoughts on this.

**Comment by victortoso** [comment]
I think this is reasonable. We have only the examples to guide developers wrt to creating a sidecar. It isn't too hard, but some documentation plus tips & tricks might be great to have.

**Comment by cwilkers** [comment]
> If this sounds reasonable, I'd need some help figuring out which section of user guide this would fit in - a separate section of its own under "Operations" tab, or under something existing?

To be honest, we still haven't gotten the re-organization of the website under way. I think our issue and PR for that staled out, and it will take some concentrated effort to make things more clear for exactly this question... For now, I think a separate section under Operations makes sense.

**Comment by dharmit** [comment]
Thanks folks. I'll ping you for reviews when I open the PR.

**Comment by dharmit** [comment]
> I think this is reasonable. We have only the examples to guide developers wrt to creating a sidecar. It isn't too hard, but some documentation plus tips & tricks might be great to have.

I didn't realise how right you were till I started working on this.
