### ISSUE TITLE
update NUMA doco

### ISSUE THREAD

**Issue by ianb-mp** [kubevirt/user-guide#755]
It would be good to include mention of these NUMA related items on the [NUMA page](https://kubevirt.io/user-guide/virtual_machines/numa/):
-  Topology Manager: https://kubernetes.io/docs/tasks/administer-cluster/topology-manager/ on the NUMA page. It is required e.g. where SR-IOV network adaptor VF allocation needs to be aligned with cpu/memory. Here's an issue which provides some context: https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/issues/262
- Memory Manager: https://kubernetes.io/docs/tasks/administer-cluster/memory-manager/

**Comment by xpivarc** [comment]
Hi @ianb-mp ,
Would you like to contribute this?

**Comment by ianb-mp** [comment]
Hi @xpivarc I sent a PR #773 3 weeks ago. Could you please take a look?

**Comment by xpivarc** [comment]
> Hi @xpivarc I sent a PR #773 3 weeks ago. Could you please take a look?

I missed the notification. Thank you for contribution
