### ISSUE TITLE
Add how to retrieve the version of the hook sidecar shim version from kubevirt cr

### ISSUE THREAD

**Issue by alicefr** [kubevirt/user-guide#775]
**Is your feature request related to a problem? Please describe**:
Since https://github.com/kubevirt/kubevirt/pull/11272 we added the sidecar shim into the kubevirt CR status. In this way, it is possible to understand the shim sidecar hooks related to the deployed kubevirt version. This is a useful information for the users to understand which image they should use with sidecar.

**Describe the solution you'd like**:
Add in the [hook sidecar documentation](https://kubevirt.io/user-guide/operations/hook-sidecar/) how to retrieve the tag of the sidecar shim image from KubeVirt CR.

**Comment by tiraboschi** [comment]
I think that this is confusing: the whole idea behind #11272 is exactly about making the image field optional in the annotation for the hook sidecar.
So, if the image field is omitted, the controller will automatically choose the most appropriate sidecarShimImage without having the user explicitly choosing it.
So we should simply amend https://github.com/kubevirt/user-guide/blob/main/docs/operations/hook-sidecar.md adding that the image can be safely omitted.

**Comment by victortoso** [comment]
I think this can be useful, although not sure where we should store and request such information. Note that we should consider:
- In the future, the image can be changed/upgraded.
- The hook sidecar version can change too.
- Not necessarily the user is using the default image brought by https://github.com/kubevirt/kubevirt/pull/11272

But I don't get why this is on user-guide, should probably be added to https://github.com/kubevirt/kubevirt/issues/11215

**Comment by alicefr** [comment]
@victortoso the idea behind documenting this was to get the right image to specify in the sidecar options. However, if this is now automatically detected, then this might not be necessary anymore

**Comment by tiraboschi** [comment]
> * In the future, the image can be changed/upgraded.
> * The hook sidecar version can change too.

Upgrades are implicitly handled in what Dharmit implemented with https://github.com/kubevirt/kubevirt/pull/11272

An environmental variable named SIDECAR_SHIM_IMAGE in the deployment of virtual-operator and virt-controller will always point to the most appropriate image.
The value of that variable is set at manifest render time during the release process exactly as for the other images.
So, if the user will not override it explicitly requiring a custom image with the annotation on the VM object, the virt-controller will take a value for SIDECAR_SHIM_IMAGE that is implicitly in pair with its own release. 

Kubevirt is also implementing a mechanism named workload upgrade strategy that is live migrating relevant  VMs to a new virt-launcher pod that has been rendered by an up-to-date virt-controller.
I'd expect this to cover also the SIDECAR_SHIM_IMAGE as for Dharmit implementation: if a specific sidecar shim image is not required, the up to date virt-controller will render the template of the destination pod consuming the actual value of `os.Getenv(operatorutil.SidecarShimImageEnvName)`, see:
https://github.com/kubevirt/kubevirt/pull/11272/files#diff-e2b17b934fcd4fb2278da4c106432d96e03f936e34e2dd4854843501aa719ad8R694-R696

So also the sidecar shim image will be upgraded as part of the workload upgrade strategy.
